### ISSUE TITLE
Rooms class broke. (Error message in comments)

### ISSUE THREAD

**Issue by kyleyjackson** [kyleyjackson/Zorkgreus-ISP#3]

**Comment by kyleyjackson** [comment]
java.lang.NullPointerException
        at Zorkgreus.Game.initRooms(Game.java:58)    
        at Zorkgreus.Game.<init>(Game.java:24)       
        at Zorkgreus.Zorkgreus.main(Zorkgreus.java:5)

Welcome to Zork!
Zork is a new, incredibly boring adventure game.
Type 'help' if you need help.

Exception in thread "main" java.lang.NullPointerException
        at Zorkgreus.Game.printWelcome(Game.java:123)    
        at Zorkgreus.Game.play(Game.java:98)
        at Zorkgreus.Zorkgreus.main(Zorkgreus.java:6)

**Comment by hcazz1n** [comment]
Fixed. Trying to get the JSON values keyId, isLocked, and isOpen in initRooms but do not exist in JSON file.
